### ISSUE TITLE
Not able to make edits to cronjob

### ISSUE THREAD

**Issue by lancekavalsky** [ArjunaCluster/HerculesUsers#15]
When trying to make edits to my cronjobs it is giving me the following error:

```
>>> crontab -e
crontab: installing new crontab
/var/spool/cron/#tmp.c01.hercules.XXXXo2rREG: No space left on device
crontab: edits left in /tmp/crontab.nTz7Za
```

From a quick google search it looks like perhaps `/var` is full? If so, I'm not sure what I can and cannot delete
(https://stackoverflow.com/questions/31283942/cronjob-no-space-left-on-device)

**Comment by aabills** [comment]
based on `df -h`, the head node's local drive is full. Usually this is due to a log that has overflowed. I'd start by running `sudo du` from `/`. Exclude `/home/` and it will go much faster

**Comment by aabills** [comment]
ping me on slack with any specific questions about what you can delete

**Comment by lancekavalsky** [comment]
some of the log files in `/var/log` became too large. @abillscmu cleared the relevant ones which resolved this. thanks!
